### ISSUE TITLE
Adding Surface QG dynamics?

### ISSUE THREAD

**Issue by BrodiePearson** [FourierFlows/GeophysicalFlows.jl#106]
Are there plans to include a SurfaceQG model in GeophysicalFlows, to complement the other 2D and QG systems that can be modelled? 

I started making an SQG model for GeophysicalFlows and I'd be happy to share/collaborate on it if there is not one already being developed. [A very rough example code is here](https://github.com/BrodiePearson/GeophysicalFlows.jl/blob/SQG-model/examples/Surface_QG_Capet.jl), and the `SurfaceQG.jl` file is also in that branch. It produces flow fields that look reasonable but I am still working to reproduce the results of a specific paper. I'd be happy to put together a doc of the equation set I'm trying to solve if that would be helpful (it is essentially the Equations of Section 2.1 [in this paper](https://archimer.ifremer.fr/doc/2008/publication-4623.pdf)).

**Comment by navidcy** [comment]
We don't have any such plans at the moment so feel free to continue work on `SurfaceQG.jl`. Ping us if you run into trouble or you want to chat about anything!

**Comment by glwagner** [comment]
I have no plans!

I'd suggest opening a PR sooner rather than later so we can collaborate on the new module + docs!

The main challenge is coming up with dynamics / physics unit tests. For example, for two-dimensional turbulence we use the Lamb dipole: 

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/5f7795c7c59435e9879a3dd1e2a004e5cb5ba8fa/test/test_twodnavierstokes.jl#L1-L21

Perhaps there's a simple analogue for SQG, or we can come up with something else.  Often such tests are nice sanity checks to have in place before publishing anything, too. @BrodiePearson have you come up with any tests?

It'd be fun to make an example out of a script that reproduces the results of the paper, too.
