### ISSUE TITLE
Convention for the hypoviscosity order: should it be positive or negative

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#115]
At the moment, the code assumes that hypoviscosity order must is negative; see, e.g.,
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/47a2b51def8af38b727dd64542c87051f169d5ea/src/twodnavierstokes.jl#L93
but the Docs in some places imply that it is positive, e.g.,
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/47a2b51def8af38b727dd64542c87051f169d5ea/docs/src/modules/twodnavierstokes.md#L32

Let's choose one of the two conventions and smooth out everything in source code, examples, and docs (across all modules). Opinions?

**Comment by glwagner** [comment]
It's not really hypoviscosity but a "second viscosity".

I think it's better to have the primary and secondary viscosity use the same sign convention.

Note that there's nothing that prevents one from using a negative exponent in the primary viscosity, either.

The point of having two viscosities is just flexibility and since we can't dictate that one is "hyper" and one is "hypo", I don't think we should imply anything of the sort.  We should point out that this is the intent of this feature, however. Users may also specify Laplacian viscosity and a high-order hyperviscosity.

**Comment by navidcy** [comment]
sure... fair point

**Comment by BrodiePearson** [comment]
I agree that it should have the same sign convention as the first.

One route in the code is to refer to one as small-scale viscosity and the other as large-scale viscosity by convention. In the Docs it could then be stated that 
> they are both viscosities and typically one is chosen to act at small scales (n\nu >=1) and the other at large scales (n\mu<=0) with the convention here that \nu acts at small-scales and \mu acts at large-scales. Some common choices are n\nu =1 (molecular-style viscosity) and n\mu=0 (linear drag), while values of n\nu>=2 and m\mu<=-1 are referred to as hyper- and hypo-viscosities respectively.

**Comment by navidcy** [comment]
Now I noticed, that with the same sign convention, the `energy_drag` and `energy_dissipation` diagnostics are superfluous...

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/9ccea29c9f06c8bc5720f1f34c4b052cb9f6af13/src/twodnavierstokes.jl#L269-L281

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/9ccea29c9f06c8bc5720f1f34c4b052cb9f6af13/src/twodnavierstokes.jl#L343-L357

They can be combine into a single function with an optional keyword argument? @glwagner any suggestion on what would be the most efficient way to do that? Can we dispatch on the parameter variable name? `params.ν` vs `params.μ`?

**Comment by BrodiePearson** [comment]
@navidcy You're right about the drag/dissipation being indistinguishable with the same sign convention.

An alternative approach (outlined below) could be to have only one viscous input with two properties (viscosity ``ν`` and order ``nν``). Since you and @glwagner have more experience with this code maybe you'll know if this is a bad idea or if it would be require significant effort. 

- The two viscous properties could be scalars (e.g. a hyper-viscosity ``ν=10^5`` and order ``nν=8``) 
- Or they could be vectors (e.g. hyper- and hypo-viscosity ``ν=[10^5, 10^20]`` and order ``nν=[8, -2]``) 
- If they are vectors each element would add another dissipative term to the budget, and there could be one dissipation diagnostic with an extra dimension denoting that viscosity element that produced it.
- This would be agnostic to the type of dissipation and more generalizable (maybe someone wants 10 different types of viscosity operator acting at once...), 
- **But I am not sure whether it would simplify the code** (e.g. would the calculation of multiple dissipative budget terms slow the code down, could the multiple dissipation diagnostics be calculated efficiently, and would separate diagnostics/budget functions be required depending on the shape of the inputs?).

**Comment by navidcy** [comment]
@BrodiePearson I think you took this one level up :)
I was only referring to the boiler plate for the two diagnostics, `energy_drag` and `energy_dissipation`.

I cleared up the boiler-plate with 28a4a76.

**Comment by navidcy** [comment]
Your suggestion above is nice but perhaps let's leave it for a future PR and not #174...

**Comment by glwagner** [comment]
@BrodiePearson's suggestion of using a single viscosity object is a good one. You might maximize performance with tuples rather than arrays (since the length of a tuple is known statically, you can dispatch / unroll loops over tuples).
