### ISSUE TITLE
Launching the example "2D dcaying turbulence" in binder does not work

### ISSUE THREAD

**Issue by ranocha** [FourierFlows/GeophysicalFlows.jl#203]
I get 
![image](https://user-images.githubusercontent.com/12693098/109988712-17f3dc00-7d08-11eb-90c0-4022bc91e305.png)

**Comment by navidcy** [comment]
Pfff... this is unfortunately due to the large size the gh-pages branch has reached...

You see, the way the binder urls work in Documenter.jl via Literate.jl (as far as I understand at least -- I may be wrong) is that it makes a clone of the documentation gh-pages repository, from which they get the `.toml` files to build the environment. Due to 1) the large number of examples we have incorporated into the Docs which include animations and 2) the several GeophysicalFlows.jl releases we made, the gh-pages branch size has become >1GB and thus binder errors!

I don't really know how to alleviate this problem. I've tried many times to clean up the gh-pages branch, asked around in slack and googled a lot... Still haven't figure how to deal with this in a simple manner. It gives me bad dreams... :)

Perhaps @mortenpi or @fredrikekre have some idea on how to make this work? If not, I'm tempted to simply remove the binder urls from the examples in the Documentation.

**Comment by mortenpi** [comment]
If the issue is the size of the `gh-pages` branch (which you can't really reduce, since you want the examples etc), I think the only way to make it work would be to store the notebooks in a separate repository. You'd need to customise `docs/make.jl` quite a bit to make that work though.
