### ISSUE TITLE
Diagnostics slow down modules running on GPU by a lot

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#69]
there must be something the gives GPU a serious bottleneck in `diagnostics.jl` in [FourierFlows.jl](https://github.com/FourierFlows/FourierFlows.jl)

Where I run this [test script](https://gist.github.com/navidcy/5ff351ad5b63b64cd428ed0cafe99629) I get:

```julia
we time-step without diagnostics
step: 0400, t: 1, walltime: 0.87 sec
step: 0800, t: 2, walltime: 1.66 sec
step: 1200, t: 2, walltime: 2.45 sec
step: 1600, t: 3, walltime: 3.24 sec
step: 2000, t: 4, walltime: 4.03 sec

re-initialize and run again with diagnostics
step: 0400, t: 1, walltime: 135.30 sec
step: 0800, t: 2, walltime: 305.39 sec
step: 1200, t: 2, walltime: 459.79 sec
step: 1600, t: 3, walltime: 599.51 sec
step: 2000, t: 4, walltime: 770.04 sec
```

If, on the other hand, I run on CPU the slowdown I get is just 1-2%.

**Comment by glwagner** [comment]
I bet its the functions `energy` and `enstrophy` that are the issue, rather than `diagnostics.jl` in FourierFlows. We can test this by using a trivial diagnostic, say, `trivial(prob) = 1`, and see if we observe the same slow down on the GPU. Since `trivial(prob) = 1` does not involve GPU computation, I'd guess that its probably not `diagnostics.jl`.

**Comment by navidcy** [comment]
I did that:

```
we time-step without diagnostics
step: 0400, t: 1, walltime: 5.29 sec
step: 0800, t: 2, walltime: 6.27 sec
step: 1200, t: 2, walltime: 9.57 sec
step: 1600, t: 3, walltime: 10.48 sec
step: 2000, t: 4, walltime: 11.32 sec

re-initialize and run again with trivial diagnostic
step: 0400, t: 1, walltime: 0.92 sec
step: 0800, t: 2, walltime: 1.73 sec
step: 1200, t: 2, walltime: 2.54 sec
step: 1600, t: 3, walltime: 3.37 sec
step: 2000, t: 4, walltime: 4.18 sec

re-initialize and run again with energy diagnostic
step: 0400, t: 1, walltime: 1.16 sec
step: 0800, t: 2, walltime: 2.27 sec
step: 1200, t: 2, walltime: 3.37 sec
step: 1600, t: 3, walltime: 4.47 sec
step: 2000, t: 4, walltime: 5.58 sec

and last re-initialize and run again with enstrophy diagnostic
step: 0400, t: 1, walltime: 129.00 sec
step: 0800, t: 2, walltime: 258.86 sec
...
```

[`energy`](https://github.com/FourierFlows/GeophysicalFlows.jl/blob/acc0417a3dddf0ab8353aae40ffd0e4783b58830/src/twodnavierstokes.jl#L236-L246) is OK but [`enstrophy`](https://github.com/FourierFlows/GeophysicalFlows.jl/blob/acc0417a3dddf0ab8353aae40ffd0e4783b58830/src/twodnavierstokes.jl#L248-L257) leads to slowdown. 

I guess this points towards [`parsevalsum2()`](https://github.com/FourierFlows/FourierFlows.jl/blob/971e044f082af74c6902ab72bf524ec53c0e9f62/src/utils.jl#L141-L155) vs [`parsevalsum()`](https://github.com/FourierFlows/FourierFlows.jl/blob/971e044f082af74c6902ab72bf524ec53c0e9f62/src/utils.jl#L168-L183)? Do you have any educated guess? Is it `@views` you reckon?

**Comment by navidcy** [comment]
I'm guessing that this is related to issue https://github.com/FourierFlows/FourierFlows.jl/issues/128

**Comment by glwagner** [comment]
Oh. I thought the issue was non-contiguous memory, but since `parsevalsum` is fine, I guess that means its something else. 

An easy solution is just to use `parsevalsum` in `enstrophy`.

`parsevalsum2` is more of a convenience function than necessary. You could try removing `@views` (I don't see why theres an `@views` there but not on `parsevalsum`). The problem may be the `abs2` element-wise command, however.

**Comment by navidcy** [comment]
Resolved by https://github.com/FourierFlows/FourierFlows.jl/pull/165
